# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: asciidoctor.proto for package 'Asciidoctor.Server'

require 'grpc'
require_relative 'asciidoctor_pb'

module Asciidoctor
  module Server
    module AsciidoctorConverter
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'asciidoctor.AsciidoctorConverter'

        rpc :Convert, ::Asciidoctor::Server::AsciidoctorConvertRequest, ::Asciidoctor::Server::AsciidoctorConvertReply
      end

      Stub = Service.rpc_stub_class
    end
  end
end
