# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in asciidoctor_server.gemspec
gemspec

gem "rake", "~> 13.0"

gem "minitest", "~> 5.0"

gem "rubocop", "~> 1.21"

gem "grpc-tools", "~> 1.0"
