name: Install Cross compilation prerequisites
description: Install the prerequisites for cross compilation, where supported FOR LINUX ONLY and ONLY FOR ASCIIDOCTOR-SERVER

inputs:
  target:
    description: 'The target triple for the cross compilation'
    required: true

runs:
  using: "composite"
  steps:
    - if: ${{ ( ! contains(inputs.target, '-unknown-linux-') ) || runner.os != 'Linux' }}
      run: |
        echo "Cross compilation is only supported for Linux targets."
        exit 1
      shell: bash
    - name: Install cross compilation prerequisites
      shell: bash
      run: |

        ARCH=$(cut -d'-' -f1 <<< "${{ inputs.target }}")
        OTHER=$(cut -d'-' -f4 <<< "${{ inputs.target }}")
        PACKAGE_ARCH="NOPE"

        case $ARCH in
          arm)
            case $OTHER in
              gnueabihf | musleabihf)
                PACKAGE_ARCH="armhf"
                ;;
              gnueabi | musleabi)
                PACKAGE_ARCH="armel"
                ;;
              *)
                echo "Unsupported architecture: $ARCH-$OTHER"
                exit 1
                ;;
            esac
          aarch64)
            PACKAGE_ARCH="arm64"
            ;;
          x86_64)
            PACKAGE_ARCH="amd64"
            ;;
          i686)
            PACKAGE_ARCH="i386"
            ;;
          *)
            echo "Unsupported architecture: $ARCH"
            exit 1
            ;;
        esac
        export DEBIAN_FRONTEND=noninteractive
        sudo apt-get -y install crossbuild-essential-$PACKAGE_ARCH