name: Install Cross compilation prerequisites
description: Install the prerequisites for cross compilation, where supported FOR LINUX ONLY and ONLY FOR ASCIIDOCTOR-SERVER

inputs:
  target:
    description: 'The target triple for the cross compilation'
    required: true

runs:
  using: "composite"
  steps:

    - if: startsWith(inputs.target, 'arm-unknown-linux-')
      shell: bash
      run: |
        sudo apt-get -y install gcc-arm-linux-gnueabihf

    - if: startsWith(inputs.target, 'i686-unknown-linux-')
      shell: bash
      run: |
        sudo apt-get -y install gcc-multilib

    - if: inputs.target ==  'aarch64-unknown-linux-gnu'
      shell: bash
      run: |
        sudo apt-get -y install gcc-aarch64-linux-gnu gcc-multilib