// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: proto/asciidoctor.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AsciidoctorConvertRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Extensions []string `protobuf:"bytes,3,rep,name=extensions,proto3" json:"extensions,omitempty"`
	Backend    string   `protobuf:"bytes,4,opt,name=backend,proto3" json:"backend,omitempty"`
	Attributes []string `protobuf:"bytes,2,rep,name=attributes,proto3" json:"attributes,omitempty"`
	Input      string   `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
}

func (x *AsciidoctorConvertRequest) Reset() {
	*x = AsciidoctorConvertRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_asciidoctor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AsciidoctorConvertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AsciidoctorConvertRequest) ProtoMessage() {}

func (x *AsciidoctorConvertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asciidoctor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AsciidoctorConvertRequest.ProtoReflect.Descriptor instead.
func (*AsciidoctorConvertRequest) Descriptor() ([]byte, []int) {
	return file_proto_asciidoctor_proto_rawDescGZIP(), []int{0}
}

func (x *AsciidoctorConvertRequest) GetExtensions() []string {
	if x != nil {
		return x.Extensions
	}
	return nil
}

func (x *AsciidoctorConvertRequest) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

func (x *AsciidoctorConvertRequest) GetAttributes() []string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *AsciidoctorConvertRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

type AsciidoctorConvertReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Output string `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
}

func (x *AsciidoctorConvertReply) Reset() {
	*x = AsciidoctorConvertReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_asciidoctor_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AsciidoctorConvertReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AsciidoctorConvertReply) ProtoMessage() {}

func (x *AsciidoctorConvertReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asciidoctor_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AsciidoctorConvertReply.ProtoReflect.Descriptor instead.
func (*AsciidoctorConvertReply) Descriptor() ([]byte, []int) {
	return file_proto_asciidoctor_proto_rawDescGZIP(), []int{1}
}

func (x *AsciidoctorConvertReply) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

var File_proto_asciidoctor_proto protoreflect.FileDescriptor

var file_proto_asciidoctor_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x73, 0x63, 0x69, 0x69, 0x64, 0x6f, 0x63,
	0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x61, 0x73, 0x63, 0x69, 0x69,
	0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x22, 0x8b, 0x01, 0x0a, 0x19, 0x41, 0x73, 0x63, 0x69, 0x69,
	0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73,
	0x69, 0x6f, 0x6e, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x12, 0x1e,
	0x0a, 0x0a, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x0a, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69,
	0x6e, 0x70, 0x75, 0x74, 0x22, 0x31, 0x0a, 0x17, 0x41, 0x73, 0x63, 0x69, 0x69, 0x64, 0x6f, 0x63,
	0x74, 0x6f, 0x72, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x16, 0x0a, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x32, 0x71, 0x0a, 0x14, 0x41, 0x73, 0x63, 0x69, 0x69,
	0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x65, 0x72, 0x12,
	0x59, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x12, 0x26, 0x2e, 0x61, 0x73, 0x63,
	0x69, 0x69, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x41, 0x73, 0x63, 0x69, 0x69, 0x64, 0x6f,
	0x63, 0x74, 0x6f, 0x72, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x24, 0x2e, 0x61, 0x73, 0x63, 0x69, 0x69, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72,
	0x2e, 0x41, 0x73, 0x63, 0x69, 0x69, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x43, 0x6f, 0x6e, 0x76,
	0x65, 0x72, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x41, 0x5a, 0x29, 0x69, 0x6f,
	0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x68, 0x79, 0x62, 0x72, 0x61, 0x73, 0x2f, 0x61,
	0x73, 0x63, 0x69, 0x69, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0xea, 0x02, 0x13, 0x41, 0x73, 0x63, 0x69, 0x69, 0x64,
	0x6f, 0x63, 0x74, 0x6f, 0x72, 0x3a, 0x3a, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_asciidoctor_proto_rawDescOnce sync.Once
	file_proto_asciidoctor_proto_rawDescData = file_proto_asciidoctor_proto_rawDesc
)

func file_proto_asciidoctor_proto_rawDescGZIP() []byte {
	file_proto_asciidoctor_proto_rawDescOnce.Do(func() {
		file_proto_asciidoctor_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_asciidoctor_proto_rawDescData)
	})
	return file_proto_asciidoctor_proto_rawDescData
}

var file_proto_asciidoctor_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_asciidoctor_proto_goTypes = []interface{}{
	(*AsciidoctorConvertRequest)(nil), // 0: asciidoctor.AsciidoctorConvertRequest
	(*AsciidoctorConvertReply)(nil),   // 1: asciidoctor.AsciidoctorConvertReply
}
var file_proto_asciidoctor_proto_depIdxs = []int32{
	0, // 0: asciidoctor.AsciidoctorConverter.Convert:input_type -> asciidoctor.AsciidoctorConvertRequest
	1, // 1: asciidoctor.AsciidoctorConverter.Convert:output_type -> asciidoctor.AsciidoctorConvertReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_asciidoctor_proto_init() }
func file_proto_asciidoctor_proto_init() {
	if File_proto_asciidoctor_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_asciidoctor_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AsciidoctorConvertRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_asciidoctor_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AsciidoctorConvertReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_asciidoctor_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_asciidoctor_proto_goTypes,
		DependencyIndexes: file_proto_asciidoctor_proto_depIdxs,
		MessageInfos:      file_proto_asciidoctor_proto_msgTypes,
	}.Build()
	File_proto_asciidoctor_proto = out.File
	file_proto_asciidoctor_proto_rawDesc = nil
	file_proto_asciidoctor_proto_goTypes = nil
	file_proto_asciidoctor_proto_depIdxs = nil
}
