#!/usr/bin/env ruby

require "asciidoctor-server"

require "asciidoctor"
require "logger"
require "grpc"

module MyLogger
  LOGGER = Logger.new $stderr, level: Logger::INFO
  def logger
    LOGGER
  end
end

# Define a gRPC module-level logger method before grpc/logconfig.rb loads.
module GRPC
  extend MyLogger
end

def main
  addr = 'unix:///Users/hybras/Documents/asciidoctor-server/socket.sock'
  # addr = "localhost:50051"
  s = GRPC::RpcServer.new
  s.add_http2_port(addr, :this_port_is_insecure)
  s.handle(Asciidoctor::Server::AsciidoctorServer)
  # Runs the server with SIGHUP, SIGINT and SIGTERM signal handlers to
  #   gracefully shutdown.
  # User could also choose to run server via call to run_till_terminated
  s.run_till_terminated_or_interrupted([1, 'int', 'SIGTERM'])
end

main