name: Publish CI artifacts
on:
  push:
    tags: ['v*']
  workflow_dispatch:

env:
  RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install rubygems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.4'
          bundler-cache: true
          working-directory: server
      - name: Install rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: '1.72.0'
          profile: minimal
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.2'

