name: Upgrade deps
on:
  schedule:
    # The "*" (#42, asterisk) character has special semantics in YAML, so this
    # string has to be quoted.
    - cron: '0 0 3 * *'
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.6.0
      - name: Renovate
        uses: renovatebot/github-action@v39.1.3
        with:
          configurationFile: renovate.json
          token: ${{ secrets.GITHUB_TOKEN }}
